name: sanayi_turbo
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  email_validator: ^2.1.17
  firebase_storage: ^11.6.0
  uuid: ^4.3.3
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  grock: ^0.5.5
  flutter_local_notifications: ^16.3.1+1
  get: ^4.6.6
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"